<?php

declare(strict_types=1);

namespace PackageVersions;

use OutOfBoundsException;

/**
 * This class is generated by composer/package-versions-deprecated, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
    const ROOT_PACKAGE_NAME = 'laravel/laravel';
    /**
     * Array of all available composer packages.
     * Dont read this array from your calling code, but use the \PackageVersions\Versions::getVersion() method instead.
     *
     * @var array<string, string>
     * @internal
     */
    const VERSIONS          = array (
  'aws/aws-sdk-php' => '3.142.0@0d1c6f5cc98640af39c0ea77f329ada775b70fe6',
  'barryvdh/laravel-debugbar' => '2.4.x-dev@e22625ed20c1fedf0a9aa88f97d5a0f9386c7988',
  'barryvdh/laravel-dompdf' => 'v0.8.2@7dcdecfa125c174d0abe723603633dc2756ea3af',
  'classpreloader/classpreloader' => '3.2.x-dev@297db07cabece3946f4a98d23f11f90aa10e1797',
  'clue/stream-filter' => 'v1.4.1@5a58cc30a8bd6a4eb8f856adf61dd3e013f53f71',
  'cocur/slugify' => '1.4.x-dev@d9694613cd4ba99fe420ac90f9b33d824ce79f36',
  'composer/package-versions-deprecated' => 'dev-master@11f0f3739d0c19fcf872810bf83cde1e8892f804',
  'cviebrock/eloquent-sluggable' => '3.1.4@5d40a334ec02c32b9c7d33f9023b5da75eb27d7d',
  'danielstjules/stringy' => '1.x-dev@4749c205db47ee5b32e8d1adf6d9aff8db6caf3b',
  'dingo/api' => 'v1.0.0-beta8@46cffad61942caa094dd876155e503b6819c5095',
  'dingo/blueprint' => 'v0.2.4@1dc93b8ea443fbbdaaca0582572ee6ca53afccfd',
  'dnoegel/php-xdg-base-dir' => '0.1@265b8593498b997dc2d31e75b89f053b5cc9621a',
  'doctrine/annotations' => 'dev-master@8fc7b23076e6144d68379f3410bb7dcf15cdc902',
  'doctrine/cache' => 'dev-master@5c5b0e27f6a8d2e03b1bdd061bd9056c4e9d1cf6',
  'doctrine/dbal' => '2.11.x-dev@0c8528ec37cce2ce3aab157ffdb71f6fc379076d',
  'doctrine/event-manager' => '1.1.x-dev@41370af6a30faa9dc0368c4a6814d596e81aba7f',
  'doctrine/inflector' => '1.4.x-dev@4650c8b30c753a76bf44fb2ed00117d6f367490c',
  'doctrine/lexer' => 'dev-master@ec953a1b157db060fc9576a6f6b6b1865a09aac9',
  'dompdf/dompdf' => 'v0.8.5@6782abfc090b132134cd6cea0ec6d76f0fce2c56',
  'fideloper/proxy' => '3.3.4@9cdf6f118af58d89764249bbcc7bb260c132924f',
  'firebase/php-jwt' => 'v5.2.0@feb0e820b8436873675fd3aca04f3728eb2185cb',
  'giggsey/libphonenumber-for-php' => 'dev-master@476a40b044a953725d5abb75fcbfa1303fd429a2',
  'giggsey/locale' => '1.8@85a1b251bad11c986fec2a051b10d4b80a5caa1b',
  'google/apiclient' => 'dev-master@9ab9cc07f66e2c7274ea2753f102ae24d1271410',
  'google/apiclient-services' => 'v0.139@84e99f792cae7bd92b8b54c75b0ad3502d628db6',
  'google/auth' => 'v1.9.0@af4abf63988b8c74f589bee1e69ba310d3e43c6c',
  'google/cloud' => 'v0.112.0@68fc365039a0dd702a4b28ca77cbab1b4ecc9327',
  'google/common-protos' => '1.2@e730d3567c8bfd94e06b538aa291270269ee3896',
  'google/crc32' => 'v0.1.0@a8525f0dea6fca1893e1bae2f6e804c5f7d007fb',
  'google/gax' => '1.3.1@6aea9c90c32aed665d4bbf4b3b681e31ef564811',
  'google/grpc-gcp' => '0.1.5@bb9bdbf62f6ae4e73d5209d85b1d0a0b9855ff36',
  'google/protobuf' => 'v3.12.2@571f9a4ba39826a18611ae568d97b6007954c070',
  'grpc/grpc' => '1.27.0@a461cb1a975dde305c73168aa4494b90c3801c62',
  'guzzlehttp/guzzle' => '6.5.x-dev@23730ab1005ca1e760dcdfbd7d853e6c3f1035d6',
  'guzzlehttp/promises' => 'dev-master@89b1a76b7fda5853401297dc4b2a093cba1fda23',
  'guzzlehttp/psr7' => '1.x-dev@188cc82398f157483976ccf61bd04ee80afcf29c',
  'hackzilla/password-generator' => 'dev-master@22c7af49ef46d349d60af0fa30f61dd4dec53330',
  'http-interop/http-factory-guzzle' => '1.0.0@34861658efb9899a6618cef03de46e2a52c80fc0',
  'jakub-onderka/php-console-color' => 'v0.2@d5deaecff52a0d61ccb613bb3804088da0307191',
  'jakub-onderka/php-console-highlighter' => 'v0.3.2@7daa75df45242c8d5b75a22c00a201e7954e4fb5',
  'jean85/pretty-package-versions' => '1.3.0@e3517fb11b67e798239354fe8213927d012ad8f9',
  'jeremeamia/superclosure' => 'dev-master@5344ca13846e50196712c997f3426543d130ea31',
  'kylekatarnls/update-helper' => '1.2.1@429be50660ed8a196e0798e5939760f168ec8ce9',
  'laravel/framework' => '5.1.x-dev@e32e92706fe3ba26aef496d23a452750a4653725',
  'laravelcollective/html' => '5.1.x-dev@99342cc22507cf8d7178bb390c215968183993bb',
  'league/flysystem' => '1.x-dev@7106f78428a344bc4f643c233a94e48795f10967',
  'league/flysystem-aws-s3-v3' => 'dev-master@d409b97a50bf85fbde30cbc9fc10237475e696ea',
  'league/fractal' => '0.19.2@06dc15f6ba38f2dde2f919d3095d13b571190a7c',
  'maximebf/debugbar' => 'v1.14.1@64251a392344e3d22f3d21c3b7c531ba96eb01d2',
  'messagebird/php-rest-api' => 'dev-master@7667ed46cbe1d5a66a7e6a181b3bffcbb413502d',
  'michelf/php-markdown' => '1.9.0@c83178d49e372ca967d1a8c77ae4e051b3a3c75c',
  'mobiledetect/mobiledetectlib' => '2.8.34@6f8113f57a508494ca36acbcfa2dc2d923c7ed5b',
  'monolog/monolog' => '1.x-dev@3022efff205e2448b560c833c6fbbf91c3139168',
  'mtdowling/cron-expression' => 'v1.2.3@9be552eebcc1ceec9776378f7dcc085246cacca6',
  'mtdowling/jmespath.php' => 'dev-master@52168cb9472de06979613d365c7f1ab8798be895',
  'namshi/jose' => '7.2.3@89a24d7eb3040e285dd5925fcad992378b82bcff',
  'nesbot/carbon' => '1.39.1@4be0c005164249208ce1b5ca633cd57bdd42ff33',
  'nikic/php-parser' => '2.x-dev@4dd659edadffdc2143e4753df655d866dbfeedf0',
  'nubs/random-name-generator' => 'v2.1.0@7004eb1724e1c4a154553e44312b7045fe412b77',
  'paragonie/random_compat' => 'v2.0.18@0a58ef6e3146256cc3dc7cc393927bcc7d1b72db',
  'paypal/rest-api-sdk-php' => '1.13.0@192e217beed14c8e75624e821fdc8ec51e2a21f5',
  'phenx/php-font-lib' => '0.5.2@ca6ad461f032145fff5971b5985e5af9e7fa88d8',
  'phenx/php-svg-lib' => 'dev-master@16fd4d717be18d8a604f2d0c3045b35aa2f6b0a5',
  'php-http/client-common' => 'dev-master@7c27fe6ad83b1ecc4c0365370643b8c189230a2d',
  'php-http/discovery' => 'dev-master@7c36d9572934034e3e68568baa68520b122ccf0c',
  'php-http/guzzle6-adapter' => 'dev-master@bd7b4056e083b62ab98442a4459fd3f163027ec0',
  'php-http/httplug' => 'dev-master@c9b242499399ba82700bcd563b7497272cc90459',
  'php-http/message' => 'dev-master@226ba9f7a4bddb6295b9ccff5a70b54013562ff0',
  'php-http/message-factory' => 'dev-master@597f30e6dfd32a85fd7dbe58cb47554b5bad910e',
  'php-http/promise' => 'dev-master@02ee67f2346b4eec3861afec741c656f5ff717ab',
  'phpdocumentor/reflection-common' => '1.0.1@21bdeb5f65d7ebf9f43b1b25d404f87deab5bfb6',
  'phpdocumentor/reflection-docblock' => '3.3.2@bf329f6c1aadea3299f08ee804682b7c45b326a2',
  'phpdocumentor/type-resolver' => '0.4.0@9c977708995954784726e25d0cd1dddf4e65b0f7',
  'phpseclib/phpseclib' => '2.0.x-dev@51f2a9386b320b203369957305b71e000a96dde8',
  'psr/cache' => 'dev-master@b9aa2cd4dd36cec02779bee07ee9dab8bd2d07d7',
  'psr/http-client' => 'dev-master@fd5d37ae5a76ee3c5301a762faf66bf9519132ef',
  'psr/http-factory' => 'dev-master@1a2099a23a7bca67f13c0634723137a364a3ebf8',
  'psr/http-message' => 'dev-master@efd67d1dc14a7ef4fc4e518e7dee91c271d524e4',
  'psr/log' => '1.0.0@fe0936ee26643249e916849d48e3a51d5f5e278b',
  'psy/psysh' => 'v0.7.2@e64e10b20f8d229cac76399e1f3edddb57a0f280',
  'ralouphie/getallheaders' => '3.0.3@120b605dfeb996808c31b6477290a714d356e822',
  'ramsey/uuid' => '3.x-dev@7e1633a6964b48589b142d60542f9ed31bd37a92',
  'rize/uri-template' => '0.3.2@9e5fdd5c47147aa5adf7f760002ee591ed37b9ca',
  'sabberworm/php-css-parser' => '8.3.1@d217848e1396ef962fb1997cf3e2421acba7f796',
  'sentry/sdk' => '2.1.0@18921af9c2777517ef9fb480845c22a98554d6af',
  'sentry/sentry' => 'dev-develop@b586900f6912a69c7743dbed268981b10500e586',
  'sentry/sentry-laravel' => '1.8.0@912731d2b704fb6a97cef89c7a8b5c367cbf6088',
  'stripe/stripe-php' => 'v6.43.1@42fcdaf99c44bb26937223f8eae1f263491d5ab8',
  'swiftmailer/swiftmailer' => '5.x-dev@181b89f18a90f8925ef805f950d47a7190e9b950',
  'symfony/console' => '2.7.x-dev@574cb4cfaa01ba115fc2fc0c2355b2c5472a4804',
  'symfony/css-selector' => '2.8.x-dev@7b1692e418d7ccac24c373528453bc90e42797de',
  'symfony/debug' => '2.7.x-dev@4a7330f29b3d215f8bacf076689f9d1c3d568681',
  'symfony/deprecation-contracts' => 'dev-master@5e20b83385a77593259c9f8beb2c43cd03b2ac14',
  'symfony/dom-crawler' => '2.7.x-dev@d905e1c5885735ee66af60c205429b9941f24752',
  'symfony/event-dispatcher' => '2.8.x-dev@a77e974a5fecb4398833b0709210e3d5e334ffb0',
  'symfony/finder' => '2.7.x-dev@34226a3aa279f1e356ad56181b91acfdc9a2525c',
  'symfony/http-foundation' => '2.7.x-dev@b67e5cbd2bf837fb3681f2c4965826d6c6758532',
  'symfony/http-kernel' => '2.7.x-dev@435064b3b143f79469206915137c21e88b56bfb9',
  'symfony/options-resolver' => 'dev-master@f3f9b9cd067d32e61e0759fc7746390f3d4d67fd',
  'symfony/polyfill-ctype' => 'dev-master@e94c8b1bbe2bc77507a1056cdb06451c75b427f9',
  'symfony/polyfill-intl-idn' => 'dev-master@3bff59ea7047e925be6b7f2059d60af31bb46d6a',
  'symfony/polyfill-mbstring' => 'dev-master@3ed80deaf77c304010e3f637bc1842c85fd6c485',
  'symfony/polyfill-php56' => 'dev-master@e3c8c138280cdfe4b81488441555583aa1984e23',
  'symfony/polyfill-php72' => 'dev-master@f048e612a3905f34931127360bdd2def19a5e582',
  'symfony/polyfill-php80' => 'dev-master@5e30b2799bc1ad68f7feb62b60a73743589438dd',
  'symfony/polyfill-util' => 'dev-master@4afb4110fc037752cf0ce9869f9ab8162c4e20d7',
  'symfony/polyfill-uuid' => 'dev-master@6dbf0269e8aeab8253a5059c51c1760fb4034e87',
  'symfony/process' => '2.7.x-dev@eda637e05670e2afeec3842dcd646dce94262f6b',
  'symfony/routing' => '2.7.x-dev@33bd5882f201f9a3b7dd9640b95710b71304c4fb',
  'symfony/translation' => '2.7.x-dev@1959c78c5a32539ef221b3e18a961a96d949118f',
  'symfony/var-dumper' => '2.7.x-dev@6f9271e94369db05807b261fcfefe4cd1aafd390',
  'telnyx/telnyx-php' => 'v0.0.1@deec64e7ccba5d299a660deb3f5c2687749839b6',
  'twilio/sdk' => '5.42.2@0cfcb871b18a9c427dd9e8f0ed7458d43009b48a',
  'tymon/jwt-auth' => '0.5.13@d7702596adaa39b89316fff45271fff98658a9d9',
  'vlucas/phpdotenv' => '1.1.x-dev@0cac554ce06277e33ddf9f0b7ade4b8bbf2af3fa',
  'webmozart/assert' => '1.8.0@ab2cb0b3b559010b75981b1bdce728da3ee90ad6',
  'yajra/laravel-datatables-oracle' => 'v5.12.5@4cc8d86de795af03c5f320711a9645b8a295b95f',
  'doctrine/instantiator' => 'dev-master@a390fde13fc9bc2ffb73340bb8f07201a8e85af8',
  'fzaninotto/faker' => 'dev-master@5337ce5261b393937bd7aaebb21020159756a152',
  'hamcrest/hamcrest-php' => '1.2.x-dev@26968e9810ff0d1aa48f6d67a862559d92a51884',
  'mockery/mockery' => '0.9.x-dev@f356e061d8ae815cd283fdc8f4412b635044be3c',
  'phpspec/php-diff' => 'dev-master@0464787bfa7cd13576c5a1e318709768798bec6a',
  'phpspec/phpspec' => '2.5.x-dev@d8a153dcb52f929b448c0bf2cc19c7388951adb1',
  'phpspec/prophecy' => 'dev-master@451c3cd1418cf640de218914901e51b064abb093',
  'phpunit/php-code-coverage' => '2.2.x-dev@eabf68b476ac7d0f73793aada060f1c1a9bf8979',
  'phpunit/php-file-iterator' => '1.4.x-dev@730b01bc3e867237eaac355e06a36b85dd93a8b4',
  'phpunit/php-text-template' => '1.2.1@31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
  'phpunit/php-timer' => '1.0.x-dev@9513098641797ce5f459dbc1de5a54c29b0ec1fb',
  'phpunit/php-token-stream' => '1.4.x-dev@58bd196ce8bc49389307b3787934a5117db80fea',
  'phpunit/phpunit' => '4.8.36@46023de9a91eec7dfb06cc56cb4e260017298517',
  'phpunit/phpunit-mock-objects' => '2.3.x-dev@ac8e7a3db35738d56ee9a76e78a4e03d97628983',
  'sebastian/comparator' => '1.2.x-dev@18a5d97c25f408f48acaf6d1b9f4079314c5996a',
  'sebastian/diff' => '1.4.x-dev@7f066a26a962dbe58ddea9f72a4e82874a3975a4',
  'sebastian/environment' => '1.3.x-dev@67f55699c2810ff0f2cc47478bbdeda8567e68ee',
  'sebastian/exporter' => '1.2.x-dev@dcd43bcc0fd3551bd2ede0081882d549bb78225d',
  'sebastian/global-state' => '1.1.x-dev@cea85a84b00f2795341ebbbca4fa396347f2494e',
  'sebastian/recursion-context' => '1.0.x-dev@b19cc3298482a335a95f3016d2f8a6950f0fbcd7',
  'sebastian/version' => '1.0.6@58b3a85e7999757d6ad81c787a1fbf5ff6c628c6',
  'symfony/yaml' => '3.3.x-dev@af615970e265543a26ee712c958404eb9b7ac93d',
  'laravel/laravel' => 'dev-master@2565c7e08831495c88f9f38058e82c249f074a91',
);

    private function __construct()
    {
    }

    /**
     * @throws OutOfBoundsException If a version cannot be located.
     *
     * @psalm-param key-of<self::VERSIONS> $packageName
     * @psalm-pure
     */
    public static function getVersion(string $packageName) : string
    {
        if (isset(self::VERSIONS[$packageName])) {
            return self::VERSIONS[$packageName];
        }

        throw new OutOfBoundsException(
            'Required package "' . $packageName . '" is not installed: check your ./vendor/composer/installed.json and/or ./composer.lock files'
        );
    }
}
