#! /usr/bin/node
var typestring = require("typestring");
var result = typestring.compile(`declare class LineCell {
  public getEventVariable(name: string,defaultValue: string): object;
  public setEventVariable(name: string): object;
}
declare class LineChannel {}
declare class LineFlow {
  public getCellByName(name: string): LineCell;
}
module.exports = function(channel: LineChannel, cell: LineCell, flow: LineFlow) {
  return new Promise(async function(resolve, reject) {
      var launch = flow.getCellByName("Launch");
      var example = <Date> launch.getEventVariable("start", "");
  });
}`);
console.log(result);
