@extends('layouts.app_new', ['show_drift' => FALSE])
@section('title') About :: @parent @endsection
@section('content')

            <link rel="stylesheet" href="/css/legal.css">

<body>
  <div class="mobile-navbar">
    <select class="browser-default" id="selectbox">
      <option value="/pages/privacy-policy">PRIVACY POLICY</option>
      <option value="/pages/tos" selected="">TERMS OF SERVICE</option>
    </select>
  </div>
  <div class="container legal">
    <div class="effective-date">
      <i>Last Updated: September 20, 2020</i>
    </div>
    <div class="inner">
      <div class="sidebar">
        <p><a href="/pages/privacy-policy">PRIVACY POLICY</a></p>
        <p><a href="/pages/tos" class="active">TERMS OF SERVICE</a></p>
      </div>
      <div class="content terms-page">
        <h2>LINEBLOCS TERMS OF SERVICE</h2>      
        <div class="block"> <b>This Software As A Service (Saas) Terms Of Service</b> (these “<b>Terms</b>” or this “<b>Agreement</b>”) govern the purchase of the license to the Software and access to Services (located at <a href="https://lineblocs.com">https://lineblocs.com</a>) by the Customer and its Users (“<b>you</b>”, “<b>your</b>”, and terms of similar meaning) made available by Lineblocs Ltd. (“<b>we</b>”, “<b>us</b>”, and “<b>Provider</b>”, together with the Customer, the "<b>Parties</b>", and each, a "<b>Party</b>"), made pursuant to an Order Form. </div>
        <div class="block"> By executing an Order Form, or by accessing or using the Services, you agree to be bound by these Terms, and all terms, policies and guidelines incorporated by reference in these Terms. By accessing or using the Services, you, or the entity on behalf of whom you are acting, agree to be legally bound by these Terms and all terms, policies and guidelines incorporated by reference in these Terms. If you do not agree with these Terms, you may not access or use the Services. </div>
        <div class="parent-group">
          <h1>1.	CHANGES TO THE TERMS OF SERVICE AND POLICIES</h1>
          <div>The Provider reserves the right, in its sole discretion to change, modify, replace, add or suspend portions of these Terms, the Privacy Policy and any other relevant policies at any time by posting the amended terms on the Services and emailing you at the address provided when registering for a user account. If you continue to access the Services after the amended terms are posted, you will be deemed to have accepted such changes through your continued use. If at any point you do not agree with our Terms, Privacy Policy, or any other policy, code of conduct or rules the Provider may have at that time, your licence to use the Services shall immediately terminate and you must immediately stop accessing or using the Services.</div>
        </div>
        <div class="parent-group">
          <h1>2.	DESCRIPTION OF SERVICES</h1>
          <div class="block"> <b>2.1 Services.</b> The Lineblocs Platform is a low-code, cloud-based unified communications platform that provides teams with enterprise calling, instant messaging, VoIP hosting, team workflows and other functionalities.</div>
        </div>
        <div class="parent-group">
          <h1>3.	DEFINITIONS</h1>
          <div class="block"> <b>3.1 “Administrator”</b> means a person or persons assigned by the Customer to have authority to act as an administrator of the subscription on behalf of the Customer, through which the Administrator shall (i) have the authority to configure User permissions and the Customer’s settings on the Services; and (ii) authorize the creation and deactivation of User accounts.</div>
          <div class="block"> <b>3.2 “Applicable Law”</b> means all relevant requirements, laws, statutes, codes, acts, orders, by-laws, rules, regulations, permits, licenses, authorizations, directions and agreements with all relevant government authorities, agencies, commissions, bodies or departments, having jurisdiction over this Agreement or the supply, provision or use of the Services.</div>
          <div class="block"> <b>3.3 “Customer”</b> shall mean a natural person or legal entity who is bound by the terms of the Order Form and these Terms of Service.</div>
          <div class="block"> <b>3.4 “Customer Data”</b>  means any information, data or content entered and uploaded into the Software by the Customer or any of its Users through using the Services. This includes trademarks, trade names, designs, logos and other indicia of origin that are owned or licensed by the Customer and approved by the Customer for use in connection with the Services.</div>
          <div class="block"> <b>3.5 “Fees”</b> means the fees and charges to be paid by the Customer pursuant to the Order Form and these Terms.</div>
          <div class="block"> <b>3.6 “Personal Information”</b> means any identifiable information relating to individuals, where the collection, use or disclosure of which is regulated by applicable privacy laws.</div>
          <div class="block"> <b>3.7 “Services”</b> means the use of the Software and other related services to be provided by the Provider to the Customer pursuant to the Order Form.</div>
          <div class="block"> <b>3.8 “Software”</b> means the Lineblocs Platform and any data or content made available through the Software by the Provider or its licensors that is licensed to the Customer and its authorized Users pursuant to the terms of the Order Form and this Agreement.</div>
          <div class="block"> <b>3.9 “Order Form”</b> means (i) the Lineblocs Order Form; (ii) an online order specifying the Services to be provided hereunder, that is entered into between the Customer and the Provider.</div>
          <div class="block"> <b>3.10 “Term”</b> shall have the meaning given in Section &lrm;15.1.</div>
          <div class="block"> <b>3.11 “User”</b> means an individual who agrees to these Terms and is authorized by the Customer to use the Software.</div>
        </div>
        <div class="parent-group">
          <h1>4.	PRIVACY POLICY</h1>
          <div class="block"> <b>4.1</b> By accessing the Services and submitting your Personal Information, you consent to the collection, use, transmission and disclosure of your Personal Information in accordance with our privacy policy (<b>“Privacy Policy”</b>), found <a href="/pages/privacy-policy">here</a>. </div>
        </div>
        <div class="parent-group">
          <h1>5.	USER ACCOUNTS</h1>
          <div class="block"> <b>5.1 User Accounts.</b> Upon submitting an Order Form and agreeing to these Terms, the initial Administrator of the Customer will be permitted to register for a User account. The initial Administrator may add other Administrators, authorize other User accounts and deactivate any User if the Administrator wishes to terminate access to the Service for any User. Specific features on the services may be restricted to Administrators. The Customer is solely responsible for deleting User accounts and ensuring that only authorized Users have access to the Services.</div>
          <div class="block"> <b>5.2 Registration.</b> The initial Administrator and other Users will be prompted to register for User accounts. Users agree to (a) provide and maintain accurate, full and complete information on their accounts when prompted by any requests or forms on the Software; (b) maintain the security of their password; and (c) accept all risk of unauthorized access to the information or data uploaded or inputted onto the Software. The Provider reserves the right to refuse registration of, or to cancel, User accounts that it reasonably believes violates the terms and conditions in this Agreement.</div>
          <div class="block"> <b>5.3 Social Media Registration.</b> If registration for a User account on the Services is performed through a social media account or any Third-Party Services (as defined below), the User acknowledges and agrees that (i) the Provider may access, store and use content from the social media account or Third-Party Services in accordance with the permissions granted to the Provider; and (ii) that all or parts of the content may be visible to other Users of the Services.</div>
        </div>
        <div class="parent-group">
          <h1>6.	SOFTWARE LICENSE AND RESTRICTIONS</h1>
          <div class="block"> <b>6.1 License to the Software.</b> Subject to these Terms and the Order Form, the Provider hereby grants to the Customer and its Users a non-exclusive, non-transferable, revocable license to use the Software and solely permit the Customer and its Users to use the functionality contained within the Software for legitimate commercial purposes during the Term.</div>
          <div class="block"> <b>6.2 Restrictions.</b> Except as set forth in this Agreement, the Order Form and to the extent contrary by Applicable Law: the Customer and its Users may not (a) copy, distribute, modify, create derivative works or adapt the Software or the Services except as permitted under this agreement; (b) use the Software or Services in manner that violates any Applicable Law or breaches the rights of any third-party (including intellectual property rights); (c) reverse engineer, disassemble, decompile or decode the Software or otherwise attempt to derive or gain access to the source code of the Software, in whole or in part; (d) rent, lease, lend, sell, sublicense, assign, distribute, publish, transfer or otherwise make available the Software to any person, including on or in connection with the internet or any subscription service, time-sharing, software as a service, cloud or other technology or service; (e) bypass or breach any security device, mechanism or protection used for or contained in the Services or Software; (f) replicate or recreate any part, design, function, feature or tool on the Software or the Services; (g) use, or access the Service for the purpose of building a competitive product or service or for any other competitive purposes; or (h) use the Software or Services other than for their permitted and intended uses, or in any manner not expressly permitted by the Provider’s third-party licensors.</div>
        </div>
        <div class="parent-group">
          <h1>7.	CUSTOMER RESPONSIBILITIES, REPRESENTATIONS AND WARRANTIES</h1>
          <div class="block"> <b>7.1 Customer Eligibility.</b> In order to use the Services, the Customer and its Users must be at least eighteen (18) years of age. </div>
          <div class="block"> <b>7.2 Customer Representations and Warranties.</b> The Customer represents and warrants that its use of the Services and the use of the Services by its Users will be consistent with this Agreement and comply with Applicable Law. The Customer shall be liable for the acts and omissions of any of its Users, directors, officers, employees, contractors, representatives or agents as if such act or omission were an act or omission of the Customer. The Customer represents and warrants that it has the right to enter into this Agreement and to allow the Provider to perform the Services.</div>
          <div class="block"> <b>7.3 Customer Responsibilities.</b> The Customer acknowledges and agrees that it shall be responsible for the acts and omissions of its Users on the Software. This includes (a) ensuring that Users comply with this Agreement and maintain the confidentiality of their passwords; and (b) ensuring that only authorized Users access and use the Services. The Customer accepts full liability and responsibility for the actions of anyone who uses the Services via its account with or without its permission, including activity performed on the Software through any of its Users’ accounts by an agent, representative, employee (including former employees who maintained access to the Services), or any other person acting on behalf of such User.</div>
          <div class="block"> <b>7.4 Restrictions on Use.</b> The Services are provided to the Customer for its internal business purposes. The Provider reserves the right to terminate the Customer’s licence to use the Services if the Provider determines, in its sole discretion, that the Customer or its Users engaged in reselling, transferring or redistributing the Services, or are using the Services for non-commercial purposes. The Customer and its Users may not:</div>
          <ol class="block lower-alpha">
            <li class="list-margin">post any information via the Services that is defamatory, libelous, hateful, violent, obscene, pornographic, unlawful, or otherwise offensive, as determined by The Provider in its sole discretion, whether or not such information may be protected by law;</li>
            <li class="list-margin">submit via the Services any data, software or other materials that contain any malicious code, viruses, worms, Trojan horses, defects, date bombs, time bombs or other items of a destructive nature;</li>
            <li class="list-margin">take any actions that impose an unreasonable burden on the Services’ technological infrastructure;</li>
            <li class="list-margin">submit inaccurate, false, or misleading information to the Services;</li>
            <li class="list-margin">distribute, publish, send or facilitate the sending of unsolicited mass e-mail or other messages, promotions, advertising or solicitations, including commercial advertising and informational announcements;</li>
            <li class="list-margin">remove any legal, copyright, trademark or other proprietary rights notices contained in or on materials the Customer receives or accesses pursuant to this Agreement;</li>
            <li class="list-margin">use the Services to violate the security or integrity of any network, computer or communications system, software application, or network or computing device; and/or</li>
            <li>attempt to gain unauthorized access to the Software, the server on which the Software is stored, or any server, computer or database connected to the Services.</li>
          </ol>
          <div> <b>7.5 Privacy Laws.</b> The Customer and its Users represent that (a) they will comply with all applicable privacy laws in connection with the collection, use and disclosure of Personal Information, and the provision of such Personal Information to the Provider complies with all applicable privacy laws; and (b) all individuals to whom such Personal Information relates have consented to the Provider’s collection, use and disclosure of such Personal Information for the purposes disclosed in this Agreement or the Privacy Policy. </div>
        </div>
        <div class="parent-group">
          <h1>8.	FEES</h1>
          <div class="block"> <b>8.1 Fees.</b> Fees to access and use the Services will be published on the Services and may change from time to time. By submitting an Order Form, the Client agrees to pay the Fees relevant to its selection of offerings in the Services. Unless otherwise specified, payment obligations are non-cancelable and Fees paid are non-refundable and payable in advance. Activation fees, installation Fees, usage-based Fees and overage that may apply will be specified on the Services or any relevant Order Form. </div>
          <div class="block"> <b>8.2 Taxes.</b> The Customer is responsible for all applicable federal, state, municipal, sales, goods and services, harmonized sales, value added, use, excise, other similar taxes, levies and charges not otherwise included in the Fees imposed by applicable tax authorities on the provision of Services hereunder. Those amounts are in addition to the Fees charged to access and use the Services. The Customer shall pay to the Provider such amounts which the Provider is registered to charge and collect. </div>
        </div>
        <div class="parent-group">
          <h1>9.	INVOICES AND PAYMENT</h1>
          <div class="block"> <b>9.1 Invoices and Payments.</b> The Provider shall invoice the Customer, in advance, for the Services in accordance with the terms of the Order Form. Unless otherwise indicated in the Order Form, the Customer shall pay such invoices within seven (7) calendar days of receipt. Taxes shall be identified and shown as separate items on each invoice.</div>
          <div class="block"> <b>9.2 Payment Authorization and Obligation.</b> When the Customer submits an Order Form, it authorizes the Provider to collect from it through the Customer’s selected payment method. The Customer’s authorization shall remain in force until thirty (30) days after it terminates the Provider’s authority to charge the selected payment method. If the Customer’s use of the Services is terminated in accordance with this Agreement, any unpaid Fee obligations shall be accelerated and become due and payable immediately. The Provider reserves the right to suspend the Customer’s access to the Services until such amounts are paid in full.</div>
          <div class="block"> The Customer must advise us immediately if payment method expires, it closes its account, its billing information changes, or its payment method is cancelled and replaced. Except for usage-based Fees, the Provider will bill in advance to the Customer’s payment method all Fees, taxes, charges and surcharges for the Term. The Provider reserves the right to charge all Fees to the Customer’s selected payment method.</div>
          <div class="block"> <b>9.3 Changes to Pricing.</b> From time to time the Provider may revise the pricing terms for the use of the Services. Notices of the changes shall be communicated to the Customer at least thirty (30) days in advance through the provided Registration Data and shall be deemed effective on the specified date. If the Customer does not agree to the changes, the Customer must terminate its use of the Services. By continuing to use the Services after the specified date the Customer accepts and agree to the revised pricing terms.</div>
          <div class="block"> <b>9.4 Fee Disputes.</b> The Customer must notify the Provider in writing within thirty (30) days after receiving an invoice if it wishes to dispute any of the Fees on that invoice, otherwise such dispute shall be deemed waived.</div>
        </div>
        <div class="parent-group">
          <h1>10.	INTELLECTUAL PROPERTY</h1>
          <div class="block"> <b>10.1 Ownership of the Software and Services.</b> Except for the rights and licenses granted in this Agreement, the Provider and its licensors, as applicable, shall retain all rights, title, interests, copyright, patent rights, trade secret rights, trademarks and other proprietary rights or interests (“<b>Intellectual Property Rights</b>”) in the Software and the Services. Nothing in this Agreement or the Order Form shall be deemed to transfer or convey ownership of any Intellectual Property Rights from one Party to the other, or to provide either Party with a right to use the other Party’s trade names, logos, or trademarks.</div>
          <div class="block"> <b>10.2 Ownership of Customer Data.</b> The Provider acknowledges and agrees that, as between the Parties, the Customer or its licensors are the sole and exclusive owner of the Customer Data, and that it has no right or interest in the Customer Data. The Customer Data will be collected, handled and used by the Provider only in compliance with the terms of this Agreement. The Customer grants to the Provider a non-exclusive, royalty-free, non-transferable license during the Term to use, reproduce, modify, adapt, create and otherwise exploit the Customer Data, solely for, and in connection with, its provision of the Services. The Customer represents and warrants that it has the right to provide a sublicensable license to the Provider covering any Customer Data that is obtained from third-parties.</div>
          <div class="block"> <b>10.3 Customer Feedback and Reviews.</b> The Customer grants the Provider a worldwide, perpetual, irrevocable, royalty-free license to use and incorporate into its services any suggestions, reviews, enhancement requests, recommendations, corrections or other feedback provided by the Customer or its Users relating to the operation of the Software or the Services.</div>
        </div>
        <div class="parent-group">
          <h1>11.	THIRD-PARTY SERVICES</h1>
          <div class="block"> <b>11.1 Third-Party Software and Licenses.</b> The Services contain third-party software and open-source software that may be subject to their own licences. These licences may contain additional terms and conditions. The Customer understands and acknowledges that such software is not licensed to it pursuant to the provisions of these Terms and that these Terms may not be construed to grant any such right and/or licence. The third-party software licences are incorporated into these Terms. By accepting these Terms and accessing and using the Services, the Customer also accepts these licences. To access any third-party licenses, please contact us at <a href="mailto:contact@lineblocs.com">contact@lineblocs.com</a>. </div>
          <div class="block"> <b>11.2 Hosting.</b> The Provider will cause the Software and accounts on the Services to be hosted on third-party servers maintained and operated by one or more reputable third-party service providers. The Provider will be responsible for contracting with the third-party service providers, and for paying all fees and charges of the third-party service providers. All Customer Data stored on the Services is located on servers operated by the third-party service providers based on their hosting policies.</div>
          <div class="block"> <b>11.3 Third-Party Services.</b> The Services may provide links to third-party sites and content that are not owned or monitored by the Provider (<b>“Third-Party Services”</b>). The Provider makes no representations about any Third-Party Services that may be accessed from the Services. The Provider does not endorse, approve or guarantee the accuracy of any content on the Third-Party Services, and when visiting them the Customer will no longer be governed by these Terms and our Privacy Policy. The Customer and its Users should familiarize themselves with and are responsible for reading and understanding the terms and conditions, privacy policies and data security practices of the Third-Party Services accessed. Those are the policies and practices that will apply to the use of the Third-Party Services. If the Customer or its Users choose to access any Third-Party Services, it is done at their own risk. The Provider has no control over the contents of any Third-Party Services and accept no responsibility for such services or for any loss or damage that may arise from the use of them. </div>
          <div class="block"> Links to Third-Party Services from the Services may include links to social media features that may enable Users to link, transmit or display on its own or using Third-Party Services, certain content from the Services. Users may only use these features when they are provided by the Provider and solely with respect to the content identified by the Provider.</div>
        </div>
        <div class="parent-group">
          <h1>12.	DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY</h1>
          <div class="block"> <b>12.1 DISCLAIMER OF WARRANTIES.</b> THE SERVICES, THE SOFTWARE, AND ANY FEATURES OR INFORMATION FOUND THROUGH THE SERVICES ARE PROVIDED ON AN "AS IS" BASIS, WITHOUT ANY WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. YOU UNDERSTAND AND AGREE THAT YOUR USE OF THE SERVICES AND ITS CONTENTS IS DONE SO AT YOUR OWN RISK.</div>
          <div class="block"> NEITHER THE PROVIDER NOR ITS SUBSIDIARIES, AFFILIATES, OR THEIR RESPECTIVE AGENTS OR REPRESENTATIVES MAKE ANY WARRANTY, REPRESENTATION, OR ENDORSEMENT WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, SUITABILITY, ACCURACY, CURRENCY, OR AVAILABILITY OF THE SERVICES OR ITS CONTENTS. WITHOUT LIMITING THE FOREGOING, NEITHER THE PROVIDER NOR ITS SUBSIDIARIES, AFFILIATES OR THEIR AGENTS REPRESENT NOR WARRANT THAT THE SERVICES, ITS CONTENTS, OR ANY FEATURES OR INFORMATION FOUND OR ATTAINED THROUGH THE SERVICES WILL BE ACCURATE, RELIABLE, ERROR-FREE, WITHOUT DELAY, WITHOUT LOSS OF DATA OR INFORMATION, WITHOUT DEGRADATION OF AUDIO QUALITY OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, OR THAT OUR TECHNOLOGICAL INFRASTRUCTURE THAT MAKES THE SERVICES AVAILABLE TO YOU IS FREE OF VIRUSES, MALICIOUS CODE OR OTHER TECHNOLOGICALLY HARMFUL COMPONENTS.</div>
          <div class="block"> <b>12.2 Limitation of Liability.</b> Except where such exclusions are prohibited by Applicable Law, under no circumstance will the Provider nor its subsidiaries, affiliates or their respective directors, officers, employees, agents, service providers, contractors, licensors, licensees, suppliers, or successors be liable for negligence, gross negligence, negligent misrepresentation, fundamental breach, damages of any kind, under any legal theory, including any direct, indirect, special, incidental, consequential, or punitive damages. This includes any of the foregoing resulting from, but not being limited to, intellectual property infringement, inaccuracy of the content provided by the Services, emotional distress, loss of revenue, loss of profits, loss of business or anticipated savings, loss of use, loss of goodwill, loss of data, and whether caused by tort (including negligence), breach of contract, breach of privacy, or otherwise, even if the Customer were allegedly advised or had reason to know. The Provider will also not be liable for any damages arising out of or in connection with the use, or inability to use, or reliance on the Services, its content, or any linked websites or such other Third-Party Services, materials, postings, or information thereon even if it were allegedly advised or had reason to know.</div>
          <div class="block"> In no event shall the aggregate liability of the Provider, whether in contract, warranty, tort, product liability, or any other legal theory, arising out of or relating to the use of the Services exceed any amount paid by the Customer during the three (3) months prior to the date of any claim.</div>
        </div>
        <div class="parent-group">
          <h1>13.	INDEMNIFICATION</h1>
          <div class="block"> <b>13.1 Indemnity by Customer.</b> The Customer agrees to defend, indemnify and hold the Provider, its directors, officers, employees, agents, contractors and affiliates, harmless from any claims losses, damages or liability for personal injury, death, fines, penalties, costs, expenses, lost profit, lost revenue, property damage, legal fees, and any and all other damages of whatever kind and nature relating to, resulting from, or arising out of (i) the use of the Services; (ii) any content or Customer Data inputted or uploaded to the Services by a User; (iii) the use of or inability to use the Services; (iv) the absence, failure or outage of the Services; and (v) a failure to comply with this Agreement, including any obligation to comply with Applicable Law, unless the claims or cause of action arise from the Provider’s gross negligence or wilful misconduct.</div>
          <div class="block"> <b>13.2 Indemnity by Provider.</b> The Provider agrees to defend, indemnify and hold the Customer, its directors, officers, employees, agents, contractors and affiliates, harmless from any loss, damage or liability, including all reasonable legal costs, that the Customer may incur as a result of or in connection with any third-party claim relating to or resulting from any breach by the Provider of the Provider’s obligations under this Agreement, including its obligation to comply with all Applicable Law.</div>
        </div>
        <div class="parent-group">
          <h1>14.		SECURITY OF THE SERVICES</h1>
          <div class="block"> <b>14.1 Security.</b> The Provider implements appropriate administrative, physical and technical security measures designed to protect the security and confidentiality of the Customer Data against any accidental or unauthorized destruction, alteration, access or disclosure to third parties. Although measures are taken to protect the Customer Data, the security of the Customer Data via the Services cannot be guaranteed. Any transmission of Customer Data via the Services is done so at the Customer’s own risk.</div>
        </div>
        <div class="parent-group">
          <h1>15.	TERM AND TERMINATION</h1>
          <div class="block"> <b>15.1 Term.</b> The term of this Agreement (<b>“Term”</b>) shall commence on the date the Order Form is submitted (<b>“Entry Date”</b>) by the Customer and shall continue until either Party terminates the Agreement in accordance with this Section. </div>
          <ol class="block lower-alpha">
            <li class="list-margin"><b>“Pay As You Go” Term.</b> If the Customer submits an Order Form for any “Pay As You Go” Services, the Term shall continue until either Party terminates this Agreement in accordance with this Section.</li>
            <li><b>Monthly Term.</b> If the Customer submits an Order Form for the Services on a month-to-month term, the Services shall continue for the period of time as described in the Order Form  <b>“Initial Term”</b> ) and will automatically renew for successive monthly terms (<b>“Renewal Terms”</b>), unless terminated in accordance with this Agreement.</li>
          </ol>
          <div class="block"> <b>15.2 Termination.</b> </div>
          <ol class="block lower-alpha">
            <li class="list-margin"><b>Termination for Convenience.</b> Except in the case of a month-to-month term, either Party may terminate this Agreement, for any reason, by providing at least fifteen (15) days prior written notice to the other Party. For month-to-month terms, the Customer may provide thirty (30) days prior written notice to terminate this Agreement. For clarity, if the Provider terminates the Agreement, it will refund the Customer the fees paid to it for the pro-rated unused portion of the Initial Term or the Renewal Term. However, if the Customer terminates this Agreement, it shall not be entitled to any refund.</li>
            <li><b>Termination for Cause.</b> Either Party may terminate this Agreement immediately upon notice to the other Party, if the other Party (i) materially breaches this Agreement and fails to remedy such breach within thirty (30) days after receiving written notice of the breach from the other Party; or (ii) commences bankruptcy or dissolution proceedings, has a receiver appointed for a substantial part of its assets, or ceases to operate in the ordinary course of business. Either Party may also terminate this Agreement or cease provision of the Services immediately if there is a material breach of this Agreement that is not capable of remedy. In addition, a Party may terminate this Agreement, in whole or in part, or cease provision of the Services if required to comply with Applicable Law or regulation, and such termination will not constitute a breach of this Agreement by the terminating Party.</li>
          </ol>
          <div class="block"> <b>15.3 Termination and Suspension of Users.</b> Notwithstanding any provision of these Terms, the Provider reserves the right, in its sole discretion, without any notice or liability to the Customer or any User, to (a) terminate a User’s license to use the Software, or any portion thereof; (b) block or prevent a User’s future access to and use of all or any portion of the Software; (c) change, suspend, or discontinue any aspect of the Software; and (d) impose limits on the Software. </div>
          <div class="block"> <b>15.4 Effect of Termination.</b> Upon termination of this Agreement in accordance with Section &lrm;15.2, the Customer will have no further right to access or use the Services, and each Party shall within sixty (60) days after written request return or destroy any tangible Confidential Information of the other Party within its possession or control that is not contained on the Services. Any Customer Data contained on the Services will be deleted within sixty (60) days of termination of the Term. The Customer acknowledges that it is responsible for exporting any Customer Data to which Customer desires continued access after termination, and the Provider shall have no liability for any failure of Customer to retrieve such Customer Data and no obligation to store or retain any such Customer Data after such sixty (60) day period. Following termination of the Term, the Provider may immediately deactivate the Customer’s accounts. </div>
        </div>
        <div class="parent-group">
          <h1>16.	CONFIDENTIAL INFORMATION</h1>
          <div class="block"> <b>16.1 Confidential Information. “Confidential Information”</b> means information in any form or medium (whether oral, written, electronic or other), acquired by a Party (<b>“Receiving Party”</b>) through the performance or receipt of the Services, that is reasonably considered confidential by the other Party (<b>“Disclosing Party”</b>), including, without limitation, trade secrets, inventions, software, designs, technologies, databases, information pertaining to business operations, strategies, pricing, and marketing, whether or not marked, designated or otherwise identified as being "confidential". Customer’s Confidential Information includes Customer Data. The Provider’s Confidential Information includes the Software and the Services. However, Confidential Information does not include any information that (a) is or becomes generally known to the public without breach of any obligation owed to the Disclosing Party; (b) was in the lawful possession of or was known to the Receiving Party prior to its disclosure by the Disclosing Party without breach of any obligation owed to the Disclosing Party; (c) is received from a third party without breach of any obligation owed to the Disclosing Party; or (d) is independently developed by the Receiving Party, which independent development can be shown by written evidence. </div>
          <div class="block"> <b>16.2 Receiving Party Obligations.</b> The Receiving Party agrees that it shall (a) not disclose or otherwise make available Confidential Information of the Disclosing Party to any third party without the prior written consent of the Disclosing Party; provided, however, that the Receiving Party may disclose the Confidential Information of the Disclosing Party to its partners, representatives, affiliates, subcontractors and associates on a “need to know” basis, who have been apprised of this restriction and who are themselves bound by nondisclosure obligations at least as restrictive as those set forth in this Agreement; (b) use the Confidential Information of the Disclosing Party only for the purposes of performing its obligations under the Agreement, exercising its rights under this Agreement or, in the case of the Customer, to make use of the Services and Software; and (c) promptly notify the Disclosing Party in the event it becomes aware of any loss or disclosure of any of the Confidential Information of Disclosing Party. </div>
          <div class="block"> <b>16.3 Compelled Disclosure.</b> If the Receiving Party becomes legally compelled by Applicable Law to disclose any Confidential Information, the Receiving Party shall provide: (a) prompt written notice of such requirement so that the Disclosing Party may seek, at its sole cost and expense, a protective order or other remedy; and (b) reasonable assistance, at the Disclosing Party's sole cost and expense, in opposing such disclosure or seeking a protective order or other limitations on disclosure. If a protective order cannot be obtained, the Party compelled to disclose will only disclose the portion of the Confidential Information that it is legally required to. </div>
          <div class="block"> <b>16.4 Destruction.</b> Upon the Termination of this Agreement, each Party shall comply with the other Party’s reasonable instructions regarding the destruction or return of both Party’s Confidential Information. If either Party does not provide instructions to the other, the other Party must destroy or return all Confidential Information and its copies within sixty (60) days after the Termination of this Agreement. </div>
          <div class="block"> <b>16.5 Indemnity.</b> Each Party agrees to indemnify and hold the other Party harmless from and against all loss or damage or any kind suffered by the other Party as a result of any breach of its obligations under this Section. </div>
        </div>
        <div class="parent-group">
          <h1>17.	GENERAL</h1>
          <div class="block"> <b>17.1 Governing Law.</b> This Agreement shall be governed by and construed in accordance with the laws of the Province of Alberta and the laws of Canada applicable therein, without giving effect to any choice or conflict of law provision, principle, or rule (whether of the laws of the Province of Alberta or any other jurisdiction) and notwithstanding your domicile, residence, or physical location. </div>
          <div class="block"> <b>17.2 Waiver of Class Proceedings.</b> The Customer waives any right it may have to commence or participate in any class action against the Provider related to any Disputes (as defined below) and, where applicable, the Customer also agrees to opt out of any class proceedings and expressly waive any rights to file a class action or seek relief on a class basis against the Provider. The Customer also waives any and all objections to the exercise of jurisdiction over it by such courts and to the venue of such courts. </div>
          <div class="block"> Any action or proceeding arising out of or relating to the Services and under these Terms shall be pursued through arbitration. If arbitration is prohibited by Applicable Law, then any action or claim shall be instituted in the courts of the Province of Alberta and/or the Federal Courts of Canada, and each party irrevocably submits to the exclusive jurisdiction of such courts in any such action or proceeding. </div>
          <div class="block"> <b>17.3 Survival.</b> The provisions of this Agreement relating to indemnification, limitations on liability, and which by their nature extend beyond the termination of this Agreement shall survive such termination. This includes, without limitation Section &lrm;8 (Fees), &lrm;9 (Invoices and Payment), Section &lrm;10 (Intellectual Property), Section &lrm;12 (Disclaimer of Warranties and Limitation of Liability), Section &lrm;13 (Indemnification), Section &lrm;15.4 (Termination), Section &lrm;16 (Confidential Information) and relevant provisions of Section &lrm;17 (General). </div>
          <div class="block"> <b>17.4 Dispute Resolution.</b> All controversies or claims (<b>“Disputes”</b>) arising out of these Terms shall first be negotiated in good faith by non-lawyer representatives from both parties. All Disputes that are not resolved within thirty (30) days of the initial notice to the other party shall be submitted to final and binding arbitration administered by an arbitrator with no right of appeal. The place of the arbitration shall be in the City of Calgary, in the Province of Alberta (Canada). The language of the arbitration shall be English. The arbitrator's award shall be final, and judgment may be entered upon it by any court having jurisdiction thereof. </div>
          <div class="block"> <b>17.5 Independent Contractors.</b> Nothing in this Agreement will be construed to imply a joint venture, partnership or principal-agent relationship between the Provider and the Customer, and neither Party will have the right, power or authority to obligate or bind the other in any manner whatsoever. </div>
          <div class="block"> <b>17.6 Force Majeure.</b> Neither Party will be liable to the other Party for any delay or failure to perform (except for any payment obligation) which is due to acts of God, acts of government, war, civil or military unrest, pandemic, virus, epidemic, riots, terrorism, fire, unavailability of communications or electrical power service provided by third parties, travel advisories as to health, security, flood, lockout, transportation delay, strikes or other labor difficulties, or other causes beyond its reasonable control. The parties agree that an event shall not be considered to beyond reasonable control if a reasonable business person applying due diligence in the same or similar circumstances under the same or similar obligations as the provisions of the Order Form would have put in place contingency plans to either materially mitigate or negate the effects of such event. However, in such event, both Parties will resume performance promptly after the cause of such delay or failure has been removed. </div>
          <div class="block"> <b>17.7 Currency.</b> Unless otherwise specified in the Order Form, all references to amounts of money in this Agreement refer to United States (USD) currency. </div>
          <div class="block"> <b>17.8 Notices.</b> Notices that the Provider gives to the Customer (other than notice of amendment of this Agreement), may be provided in any of the following ways. First, the Provider may email an Administrator at the contact information provided in the Order Form or any registration data. Second, the Provider may post a notice on the its website. It is the Customer’s responsibility to periodically review the Provider’s website for notices. The Customer may provide notice to the Provider by (a) submitting a ticket through the helpdesk; or (b) emailing the Provider at the address below. </div>
          <div class="block"> <b>17.9 Successors and Assigns.</b> This Agreement shall enure to the benefit of, and be binding on, the parties and their respective successors and permitted assigns. The Provider may assign all or part of its rights or duties under this Agreement. The Customer may not assign this Agreement, or its rights or obligations hereunder, without the Provider’s prior written consent. </div>
          <div class="block"> <b>17.10 Severability and Waiver.</b> This Agreement shall be deemed severable, and the invalidity or unenforceability of any term or provision and shall not affect the validity or enforceability of this Agreement or of any other term or provision in this Agreement. Should any term or provision of this Agreement be declared void or unenforceable by any court of competent jurisdiction, the Parties intend that a substitute provision will be added to this Agreement so that, to the greatest extent possible, the substitute provision achieves the intended commercial outcome of the original provision. Any failure of either Party to enforce any rights granted to it hereunder or to take action against the other Party in the event of any breach hereunder will not be deemed a waiver by that Party as to subsequent enforcement of rights or subsequent actions in the event of future breaches. </div>
          <div class="block"> <b>17.11 Entire Agreement.</b> This Agreement and the Order Form supersedes all prior agreements, negotiations and representations between the Parties regarding the subject matter of this Agreement. </div>
          <div class="block"> <b>17.12 Export Controls.</b> The Services and all related software and technical information may be subject to the United States of America’s export laws, restrictions and regulations. The Customer and its Users agree to not export, transfer, distribute, transmit or allow for the export, transfer, distribution or transmission of the Services and all related content, software and technical information, except in compliance with any and all relevant export laws, regulations and restrictions. The export, transfer, distribution or transmission of the Software and all related content, software and technical information, directly or indirectly to an embargoed or sanctions region/country is in violation of these Terms. </div>
          <div class="block"> <b>17.13 Geographic Restrictions.</b> The Provider does not provide the Services to certain countries outside of Canada and the United States of America. If the Client is using the Services in a country not support by the Provider and in violation of Applicable Law, the Client is solely liable for any violations and agree to indemnify the Provider for any and all claims, damages or losses. </div>
          <div class="block"> <b>17.14 Modification of Terms.</b> The Provider may modify this Agreement at any time by (a) posting a notice on the Provider’s website or the Services; or (b) by e-mailing the Customer and its Users. The Customer is responsible for checking the Terms whenever it accesses or use the Services. By continuing to access or use the Services, you are indicating that you agree to be bound by the modified terms. If the modified terms are not acceptable to you, you must stop accessing and using the Services. </div>
        </div>
        <div class="parent-group">
          <h1>18.	QUESTIONS</h1>
          <div class="block"> <b>18.1</b> If you have any questions regarding these Terms or your use of the Services, please contact us here:
            <p><a href="mailto:contact@lineblocs.com">contact@lineblocs.com</a></p>
          </div>
        </div>
      </div>
    </div>
    <button onclick="function topFunction() {
               document.body.scrollTop = 0; // For Safari
                 document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
         }
         topFunction()" id="scrollToTop" title="Go to top"><i class="far fa-arrow-alt-circle-up"></i></button>
  </div>

     @section('scripts')
     <script>
       jQuery(function () {
          jQuery("#selectbox").change(function () {
              location.href = jQuery(this).val();
          })
         let mybutton = document.getElementById("scrollToTop");

         // When the user scrolls down 20px from the top of the document, show the button
         window.onscroll = function() {scrollFunction()};

         function scrollFunction() {
           if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
             mybutton.style.display = "block";
           } else {
             mybutton.style.display = "none";
           }
         }
      })
     </script>
     @endsection


</body>
@endsection