<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'yajra\\Datatables' => array($vendorDir . '/yajra/laravel-datatables-oracle/src'),
    'UpdateHelper\\' => array($vendorDir . '/kylekatarnls/update-helper/src'),
    'Sentry\\Laravel\\' => array($vendorDir . '/sentry/sentry-laravel/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'PhpSpec' => array($vendorDir . '/phpspec/phpspec/src'),
    'PayPal' => array($vendorDir . '/paypal/rest-api-sdk-php/lib'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'JakubOnderka\\PhpConsoleHighlighter' => array($vendorDir . '/jakub-onderka/php-console-highlighter/src'),
    'Dotenv' => array($vendorDir . '/vlucas/phpdotenv/src'),
    'Diff' => array($vendorDir . '/phpspec/php-diff/lib'),
    'Detection' => array($vendorDir . '/mobiledetect/mobiledetectlib/namespaced'),
);
