<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '7c74cc1256c8dcfc2a905ff46176ed161bae5afe',
        'name' => 'lineblocs/admin-site',
        'dev' => true,
    ),
    'versions' => array(
        'aws/aws-crt-php' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../aws/aws-crt-php',
            'aliases' => array(),
            'reference' => '3942776a8c99209908ee0b287746263725685732',
            'dev_requirement' => false,
        ),
        'aws/aws-sdk-php' => array(
            'pretty_version' => '3.255.2',
            'version' => '3.255.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../aws/aws-sdk-php',
            'aliases' => array(),
            'reference' => 'b6b995c70b7ed4359b4310243899cbfe11a73caa',
            'dev_requirement' => false,
        ),
        'barryvdh/laravel-debugbar' => array(
            'pretty_version' => '2.4.x-dev',
            'version' => '2.4.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../barryvdh/laravel-debugbar',
            'aliases' => array(),
            'reference' => 'e22625ed20c1fedf0a9aa88f97d5a0f9386c7988',
            'dev_requirement' => false,
        ),
        'barryvdh/laravel-dompdf' => array(
            'pretty_version' => 'v0.8.2',
            'version' => '0.8.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../barryvdh/laravel-dompdf',
            'aliases' => array(),
            'reference' => '7dcdecfa125c174d0abe723603633dc2756ea3af',
            'dev_requirement' => false,
        ),
        'classpreloader/classpreloader' => array(
            'pretty_version' => '3.2.x-dev',
            'version' => '3.2.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../classpreloader/classpreloader',
            'aliases' => array(),
            'reference' => '297db07cabece3946f4a98d23f11f90aa10e1797',
            'dev_requirement' => false,
        ),
        'clue/stream-filter' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../clue/stream-filter',
            'aliases' => array(),
            'reference' => '3cd5ac57c18cf9e449682eeadd8f8fdd5b4e864f',
            'dev_requirement' => false,
        ),
        'cocur/slugify' => array(
            'pretty_version' => '1.4.x-dev',
            'version' => '1.4.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cocur/slugify',
            'aliases' => array(),
            'reference' => 'd9694613cd4ba99fe420ac90f9b33d824ce79f36',
            'dev_requirement' => false,
        ),
        'cordoval/hamcrest-php' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'cviebrock/eloquent-sluggable' => array(
            'pretty_version' => '3.1.4',
            'version' => '3.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cviebrock/eloquent-sluggable',
            'aliases' => array(),
            'reference' => '5d40a334ec02c32b9c7d33f9023b5da75eb27d7d',
            'dev_requirement' => false,
        ),
        'danielstjules/stringy' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../danielstjules/stringy',
            'aliases' => array(),
            'reference' => '4749c205db47ee5b32e8d1adf6d9aff8db6caf3b',
            'dev_requirement' => false,
        ),
        'davedevelopment/hamcrest-php' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'dingo/api' => array(
            'pretty_version' => 'v1.0.0-beta8',
            'version' => '1.0.0.0-beta8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dingo/api',
            'aliases' => array(),
            'reference' => '46cffad61942caa094dd876155e503b6819c5095',
            'dev_requirement' => false,
        ),
        'dingo/blueprint' => array(
            'pretty_version' => 'v0.2.4',
            'version' => '0.2.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dingo/blueprint',
            'aliases' => array(),
            'reference' => '1dc93b8ea443fbbdaaca0582572ee6ca53afccfd',
            'dev_requirement' => false,
        ),
        'dnoegel/php-xdg-base-dir' => array(
            'pretty_version' => '0.1',
            'version' => '0.1.0.0',
            'type' => 'project',
            'install_path' => __DIR__ . '/../dnoegel/php-xdg-base-dir',
            'aliases' => array(),
            'reference' => '265b8593498b997dc2d31e75b89f053b5cc9621a',
            'dev_requirement' => false,
        ),
        'doctrine/annotations' => array(
            'pretty_version' => '1.15.x-dev',
            'version' => '1.15.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/annotations',
            'aliases' => array(),
            'reference' => 'ad785217c1e9555a7d6c6c8c9f406395a5e2882b',
            'dev_requirement' => false,
        ),
        'doctrine/cache' => array(
            'pretty_version' => '2.2.x-dev',
            'version' => '2.2.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/cache',
            'aliases' => array(),
            'reference' => '7e6ea80079a053064d0934d468e6c2570d59dc93',
            'dev_requirement' => false,
        ),
        'doctrine/dbal' => array(
            'pretty_version' => '2.13.9',
            'version' => '2.13.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/dbal',
            'aliases' => array(),
            'reference' => 'c480849ca3ad6706a39c970cdfe6888fa8a058b8',
            'dev_requirement' => false,
        ),
        'doctrine/deprecations' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/deprecations',
            'aliases' => array(),
            'reference' => '0e2a4f1f8cdfc7a92ec3b01c9334898c806b30de',
            'dev_requirement' => false,
        ),
        'doctrine/event-manager' => array(
            'pretty_version' => '1.2.x-dev',
            'version' => '1.2.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/event-manager',
            'aliases' => array(),
            'reference' => '95aa4cb529f1e96576f3fda9f5705ada4056a520',
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '1.4.x-dev',
            'version' => '1.4.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'reference' => '4bd5c1cdfcd00e9e2d8c484f79150f67e5d355d9',
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.5.x-dev',
            'version' => '1.5.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'reference' => '10dcfce151b967d20fde1b34ae6640712c3891bc',
            'dev_requirement' => true,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '2.1.x-dev',
            'version' => '2.1.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'reference' => '5a72344bf31b6772b6a49cf75b2c653a03254ac1',
            'dev_requirement' => false,
        ),
        'dompdf/dompdf' => array(
            'pretty_version' => 'v0.8.6',
            'version' => '0.8.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dompdf/dompdf',
            'aliases' => array(),
            'reference' => 'db91d81866c69a42dad1d2926f61515a1e3f42c5',
            'dev_requirement' => false,
        ),
        'fideloper/proxy' => array(
            'pretty_version' => '3.3.4',
            'version' => '3.3.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fideloper/proxy',
            'aliases' => array(),
            'reference' => '9cdf6f118af58d89764249bbcc7bb260c132924f',
            'dev_requirement' => false,
        ),
        'firebase/php-jwt' => array(
            'pretty_version' => 'v6.3.2',
            'version' => '6.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../firebase/php-jwt',
            'aliases' => array(),
            'reference' => 'ea7dda77098b96e666c5ef382452f94841e439cd',
            'dev_requirement' => false,
        ),
        'fzaninotto/faker' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fzaninotto/faker',
            'aliases' => array(
                0 => '1.9.x-dev',
            ),
            'reference' => '5ffe7db6c80f441f150fc88008d64e64af66634b',
            'dev_requirement' => true,
        ),
        'giggsey/libphonenumber-for-php' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../giggsey/libphonenumber-for-php',
            'aliases' => array(
                0 => '8.x-dev',
            ),
            'reference' => 'f40e7696c207ec37465a9e841dd9d3b0a8e9c781',
            'dev_requirement' => false,
        ),
        'giggsey/locale' => array(
            'pretty_version' => '2.3',
            'version' => '2.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../giggsey/locale',
            'aliases' => array(),
            'reference' => '5f035523740be40d40ac768a123c9bcc1ae12f56',
            'dev_requirement' => false,
        ),
        'google/apiclient' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/apiclient',
            'aliases' => array(
                0 => '2.x-dev',
            ),
            'reference' => 'b653a338c5a658adf6df4bb2f44c2cc02fe7eb1d',
            'dev_requirement' => false,
        ),
        'google/apiclient-services' => array(
            'pretty_version' => 'v0.279.0',
            'version' => '0.279.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/apiclient-services',
            'aliases' => array(),
            'reference' => '2105f08f4ee00c5847f980b5b4491346f4ceb60d',
            'dev_requirement' => false,
        ),
        'google/auth' => array(
            'pretty_version' => 'v1.24.0',
            'version' => '1.24.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/auth',
            'aliases' => array(),
            'reference' => '1f8cff5aa324700d041efd2df1a0855112a2e7ae',
            'dev_requirement' => false,
        ),
        'google/cloud' => array(
            'pretty_version' => 'v0.112.0',
            'version' => '0.112.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/cloud',
            'aliases' => array(),
            'reference' => '68fc365039a0dd702a4b28ca77cbab1b4ecc9327',
            'dev_requirement' => false,
        ),
        'google/cloud-asset' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.4.0',
            ),
        ),
        'google/cloud-automl' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.5.0',
            ),
        ),
        'google/cloud-bigquery' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.12.0',
            ),
        ),
        'google/cloud-bigquerydatatransfer' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.14.0',
            ),
        ),
        'google/cloud-bigtable' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.1.0',
            ),
        ),
        'google/cloud-common-protos' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.2.0',
            ),
        ),
        'google/cloud-container' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.11.0',
            ),
        ),
        'google/cloud-core' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.33.0',
            ),
        ),
        'google/cloud-dataproc' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.13.0',
            ),
        ),
        'google/cloud-datastore' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.10.0',
            ),
        ),
        'google/cloud-debugger' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.19.1',
            ),
        ),
        'google/cloud-dialogflow' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.10.0',
            ),
        ),
        'google/cloud-dlp' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.22.0',
            ),
        ),
        'google/cloud-error-reporting' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.15.0',
            ),
        ),
        'google/cloud-firestore' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.8.0',
            ),
        ),
        'google/cloud-iot' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.9.0',
            ),
        ),
        'google/cloud-kms' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.7.0',
            ),
        ),
        'google/cloud-language' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.20.0',
            ),
        ),
        'google/cloud-logging' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.18.0',
            ),
        ),
        'google/cloud-monitoring' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.18.0',
            ),
        ),
        'google/cloud-oslogin' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.10.0',
            ),
        ),
        'google/cloud-pubsub' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.17.0',
            ),
        ),
        'google/cloud-redis' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.10.0',
            ),
        ),
        'google/cloud-scheduler' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.1.0',
            ),
        ),
        'google/cloud-security-center' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.2.0',
            ),
        ),
        'google/cloud-spanner' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.18.0',
            ),
        ),
        'google/cloud-speech' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.27.0',
            ),
        ),
        'google/cloud-storage' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.14.0',
            ),
        ),
        'google/cloud-talent' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.6.0',
            ),
        ),
        'google/cloud-tasks' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.3.0',
            ),
        ),
        'google/cloud-text-to-speech' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.5.0',
            ),
        ),
        'google/cloud-trace' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.15.0',
            ),
        ),
        'google/cloud-translate' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.4.1',
            ),
        ),
        'google/cloud-videointelligence' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.7.0',
            ),
        ),
        'google/cloud-vision' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.23.0',
            ),
        ),
        'google/cloud-web-risk' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.3.0',
            ),
        ),
        'google/cloud-web-security-scanner' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '0.2.0',
            ),
        ),
        'google/common-protos' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/common-protos',
            'aliases' => array(),
            'reference' => 'b1ee63636d94fe88f6cff600a0f23fae06b6fa2e',
            'dev_requirement' => false,
        ),
        'google/crc32' => array(
            'pretty_version' => 'v0.1.0',
            'version' => '0.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/crc32',
            'aliases' => array(),
            'reference' => 'a8525f0dea6fca1893e1bae2f6e804c5f7d007fb',
            'dev_requirement' => false,
        ),
        'google/gax' => array(
            'pretty_version' => 'v1.18.1',
            'version' => '1.18.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/gax',
            'aliases' => array(),
            'reference' => '45e01473b7215d593a58a72c89225f110e9d2ce0',
            'dev_requirement' => false,
        ),
        'google/grpc-gcp' => array(
            'pretty_version' => 'v0.2.1',
            'version' => '0.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/grpc-gcp',
            'aliases' => array(),
            'reference' => '899d0112812a812df7692617a59f4076f0d01719',
            'dev_requirement' => false,
        ),
        'google/longrunning' => array(
            'pretty_version' => 'v0.2.2',
            'version' => '0.2.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/longrunning',
            'aliases' => array(),
            'reference' => 'a45f08bab4eacb185244adfc5db72f63900280f0',
            'dev_requirement' => false,
        ),
        'google/protobuf' => array(
            'pretty_version' => 'v3.21.12',
            'version' => '3.21.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/protobuf',
            'aliases' => array(),
            'reference' => '93019df2df0f8c5c01757ef79f3f077d2cb35b65',
            'dev_requirement' => false,
        ),
        'grpc/grpc' => array(
            'pretty_version' => '1.42.0',
            'version' => '1.42.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../grpc/grpc',
            'aliases' => array(),
            'reference' => '9fa44f104cb92e924d4da547323a97f3d8aca6d4',
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '6.5.x-dev',
            'version' => '6.5.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'reference' => 'a52f0440530b54fa079ce76e8c5d196a42cad981',
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(
                0 => '1.5.x-dev',
            ),
            'reference' => 'b94b2807d85443f9719887892882d0329d1e2598',
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => 'e98e3e6d4f86621a9b75f623996e6bbdeb4b9318',
            'dev_requirement' => false,
        ),
        'hackzilla/password-generator' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../hackzilla/password-generator',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '5b0a54b7e299c3dcecf619ed7b04fb0afb87e096',
            'dev_requirement' => false,
        ),
        'hamcrest/hamcrest-php' => array(
            'pretty_version' => '1.2.x-dev',
            'version' => '1.2.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../hamcrest/hamcrest-php',
            'aliases' => array(),
            'reference' => '26968e9810ff0d1aa48f6d67a862559d92a51884',
            'dev_requirement' => true,
        ),
        'http-interop/http-factory-guzzle' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../http-interop/http-factory-guzzle',
            'aliases' => array(),
            'reference' => '8f06e92b95405216b237521cc64c804dd44c4a81',
            'dev_requirement' => false,
        ),
        'illuminate/auth' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/broadcasting' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/bus' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/config' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/console' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/container' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/contracts' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/cookie' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/database' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/encryption' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/events' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/exception' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/filesystem' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/hashing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/http' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/log' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/mail' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/pagination' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/pipeline' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/queue' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/redis' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/routing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/session' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/support' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/translation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/validation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'illuminate/view' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '5.1.x-dev',
            ),
        ),
        'jakub-onderka/php-console-color' => array(
            'pretty_version' => 'v0.2',
            'version' => '0.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jakub-onderka/php-console-color',
            'aliases' => array(),
            'reference' => 'd5deaecff52a0d61ccb613bb3804088da0307191',
            'dev_requirement' => false,
        ),
        'jakub-onderka/php-console-highlighter' => array(
            'pretty_version' => 'v0.3.2',
            'version' => '0.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jakub-onderka/php-console-highlighter',
            'aliases' => array(),
            'reference' => '7daa75df45242c8d5b75a22c00a201e7954e4fb5',
            'dev_requirement' => false,
        ),
        'jean85/pretty-package-versions' => array(
            'pretty_version' => '2.x-dev',
            'version' => '2.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jean85/pretty-package-versions',
            'aliases' => array(),
            'reference' => 'ea175e0a262389d59d35802d9e32319fa64449c0',
            'dev_requirement' => false,
        ),
        'jeremeamia/superclosure' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jeremeamia/superclosure',
            'aliases' => array(
                0 => '2.4.x-dev',
            ),
            'reference' => '5b3c76c0e4c6b01cddb6e997f579a1b4c59ee8a0',
            'dev_requirement' => false,
        ),
        'kodova/hamcrest-php' => array(
            'dev_requirement' => true,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'kylekatarnls/update-helper' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../kylekatarnls/update-helper',
            'aliases' => array(),
            'reference' => '429be50660ed8a196e0798e5939760f168ec8ce9',
            'dev_requirement' => false,
        ),
        'laravel/framework' => array(
            'pretty_version' => '5.1.x-dev',
            'version' => '5.1.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/framework',
            'aliases' => array(),
            'reference' => 'e32e92706fe3ba26aef496d23a452750a4653725',
            'dev_requirement' => false,
        ),
        'laravelcollective/html' => array(
            'pretty_version' => '5.1.x-dev',
            'version' => '5.1.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravelcollective/html',
            'aliases' => array(),
            'reference' => '99342cc22507cf8d7178bb390c215968183993bb',
            'dev_requirement' => false,
        ),
        'league/flysystem' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/flysystem',
            'aliases' => array(),
            'reference' => '3239285c825c152bcc315fe0e87d6b55f5972ed1',
            'dev_requirement' => false,
        ),
        'league/flysystem-aws-s3-v3' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/flysystem-aws-s3-v3',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'reference' => 'af286f291ebab6877bac0c359c6c2cb017eb061d',
            'dev_requirement' => false,
        ),
        'league/fractal' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/fractal',
            'aliases' => array(
                0 => '0.20.x-dev',
            ),
            'reference' => '8b9d39b67624db9195c06f9c1ffd0355151eaf62',
            'dev_requirement' => false,
        ),
        'league/mime-type-detection' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/mime-type-detection',
            'aliases' => array(),
            'reference' => 'ff6248ea87a9f116e78edd6002e39e5128a0d4dd',
            'dev_requirement' => false,
        ),
        'lineblocs/admin-site' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '7c74cc1256c8dcfc2a905ff46176ed161bae5afe',
            'dev_requirement' => false,
        ),
        'maximebf/debugbar' => array(
            'pretty_version' => 'v1.14.1',
            'version' => '1.14.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maximebf/debugbar',
            'aliases' => array(),
            'reference' => '64251a392344e3d22f3d21c3b7c531ba96eb01d2',
            'dev_requirement' => false,
        ),
        'messagebird/php-rest-api' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../messagebird/php-rest-api',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'reference' => '106c61a2eaa80dcaf5d52b21ddeacbd0a59c791f',
            'dev_requirement' => false,
        ),
        'michelf/php-markdown' => array(
            'pretty_version' => '1.9.1',
            'version' => '1.9.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../michelf/php-markdown',
            'aliases' => array(),
            'reference' => '5024d623c1a057dcd2d076d25b7d270a1d0d55f3',
            'dev_requirement' => false,
        ),
        'mobiledetect/mobiledetectlib' => array(
            'pretty_version' => '2.8.41',
            'version' => '2.8.41.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mobiledetect/mobiledetectlib',
            'aliases' => array(),
            'reference' => 'fc9cccd4d3706d5a7537b562b59cc18f9e4c0cb1',
            'dev_requirement' => false,
        ),
        'mockery/mockery' => array(
            'pretty_version' => '0.9.x-dev',
            'version' => '0.9.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mockery/mockery',
            'aliases' => array(),
            'reference' => 'f356e061d8ae815cd283fdc8f4412b635044be3c',
            'dev_requirement' => true,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'reference' => '904713c5929655dc9b97288b69cfeedad610c9a1',
            'dev_requirement' => false,
        ),
        'mtdowling/cron-expression' => array(
            'pretty_version' => 'v1.2.3',
            'version' => '1.2.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mtdowling/cron-expression',
            'aliases' => array(),
            'reference' => '9be552eebcc1ceec9776378f7dcc085246cacca6',
            'dev_requirement' => false,
        ),
        'mtdowling/jmespath.php' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mtdowling/jmespath.php',
            'aliases' => array(
                0 => '2.6.x-dev',
            ),
            'reference' => '9b87907a81b87bc76d19a7fb2d61e61486ee9edb',
            'dev_requirement' => false,
        ),
        'namshi/jose' => array(
            'pretty_version' => '7.2.3',
            'version' => '7.2.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../namshi/jose',
            'aliases' => array(),
            'reference' => '89a24d7eb3040e285dd5925fcad992378b82bcff',
            'dev_requirement' => false,
        ),
        'nesbot/carbon' => array(
            'pretty_version' => '1.39.1',
            'version' => '1.39.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nesbot/carbon',
            'aliases' => array(),
            'reference' => '4be0c005164249208ce1b5ca633cd57bdd42ff33',
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => '2.x-dev',
            'version' => '2.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'reference' => '4dd659edadffdc2143e4753df655d866dbfeedf0',
            'dev_requirement' => false,
        ),
        'nubs/random-name-generator' => array(
            'pretty_version' => 'v2.2.0',
            'version' => '2.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nubs/random-name-generator',
            'aliases' => array(),
            'reference' => '50abf24519badc5795a43c831f1d2a1faa45cb77',
            'dev_requirement' => false,
        ),
        'paragonie/constant_time_encoding' => array(
            'pretty_version' => 'v2.6.3',
            'version' => '2.6.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/constant_time_encoding',
            'aliases' => array(),
            'reference' => '58c3f47f650c94ec05a151692652a868995d2938',
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v2.0.21',
            'version' => '2.0.21.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'reference' => '96c132c7f2f7bc3230723b66e89f8f150b29d5ae',
            'dev_requirement' => false,
        ),
        'paypal/rest-api-sdk-php' => array(
            'pretty_version' => '1.13.0',
            'version' => '1.13.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paypal/rest-api-sdk-php',
            'aliases' => array(),
            'reference' => '192e217beed14c8e75624e821fdc8ec51e2a21f5',
            'dev_requirement' => false,
        ),
        'phenx/php-font-lib' => array(
            'pretty_version' => '0.5.4',
            'version' => '0.5.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phenx/php-font-lib',
            'aliases' => array(),
            'reference' => 'dd448ad1ce34c63d09baccd05415e361300c35b4',
            'dev_requirement' => false,
        ),
        'phenx/php-svg-lib' => array(
            'pretty_version' => '0.3.4',
            'version' => '0.3.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phenx/php-svg-lib',
            'aliases' => array(),
            'reference' => 'f627771eb854aa7f45f80add0f23c6c4d67ea0f2',
            'dev_requirement' => false,
        ),
        'php-http/async-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
            ),
        ),
        'php-http/client-common' => array(
            'pretty_version' => '2.6.0',
            'version' => '2.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/client-common',
            'aliases' => array(),
            'reference' => '45db684cd4e186dcdc2b9c06b22970fe123796c0',
            'dev_requirement' => false,
        ),
        'php-http/client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
            ),
        ),
        'php-http/discovery' => array(
            'pretty_version' => '1.14.3',
            'version' => '1.14.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/discovery',
            'aliases' => array(),
            'reference' => '31d8ee46d0215108df16a8527c7438e96a4d7735',
            'dev_requirement' => false,
        ),
        'php-http/httplug' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/httplug',
            'aliases' => array(
                0 => '2.x-dev',
            ),
            'reference' => 'f640739f80dfa1152533976e3c112477f69274eb',
            'dev_requirement' => false,
        ),
        'php-http/message' => array(
            'pretty_version' => '1.13.0',
            'version' => '1.13.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/message',
            'aliases' => array(),
            'reference' => '7886e647a30a966a1a8d1dad1845b71ca8678361',
            'dev_requirement' => false,
        ),
        'php-http/message-factory' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/message-factory',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'reference' => '597f30e6dfd32a85fd7dbe58cb47554b5bad910e',
            'dev_requirement' => false,
        ),
        'php-http/message-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'php-http/promise' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/promise',
            'aliases' => array(
                0 => '1.1.x-dev',
            ),
            'reference' => '4c4c1f9b7289a2ec57cde7f1e9762a5789506f88',
            'dev_requirement' => false,
        ),
        'phpdocumentor/reflection-common' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-common',
            'aliases' => array(),
            'reference' => '21bdeb5f65d7ebf9f43b1b25d404f87deab5bfb6',
            'dev_requirement' => false,
        ),
        'phpdocumentor/reflection-docblock' => array(
            'pretty_version' => '3.3.2',
            'version' => '3.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-docblock',
            'aliases' => array(),
            'reference' => 'bf329f6c1aadea3299f08ee804682b7c45b326a2',
            'dev_requirement' => false,
        ),
        'phpdocumentor/type-resolver' => array(
            'pretty_version' => '0.4.0',
            'version' => '0.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/type-resolver',
            'aliases' => array(),
            'reference' => '9c977708995954784726e25d0cd1dddf4e65b0f7',
            'dev_requirement' => false,
        ),
        'phpseclib/phpseclib' => array(
            'pretty_version' => '3.0.x-dev',
            'version' => '3.0.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpseclib/phpseclib',
            'aliases' => array(),
            'reference' => 'f28693d38ba21bb0d9f0c411ee5dae2b178201da',
            'dev_requirement' => false,
        ),
        'phpspec/php-diff' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/php-diff',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'reference' => 'fc1156187f9f6c8395886fe85ed88a0a245d72e9',
            'dev_requirement' => true,
        ),
        'phpspec/phpspec' => array(
            'pretty_version' => '2.5.x-dev',
            'version' => '2.5.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/phpspec',
            'aliases' => array(),
            'reference' => 'd8a153dcb52f929b448c0bf2cc19c7388951adb1',
            'dev_requirement' => true,
        ),
        'phpspec/prophecy' => array(
            'pretty_version' => 'v1.10.3',
            'version' => '1.10.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/prophecy',
            'aliases' => array(),
            'reference' => '451c3cd1418cf640de218914901e51b064abb093',
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '2.2.4',
            'version' => '2.2.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'reference' => 'eabf68b476ac7d0f73793aada060f1c1a9bf8979',
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '1.4.x-dev',
            'version' => '1.4.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'reference' => '730b01bc3e867237eaac355e06a36b85dd93a8b4',
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'reference' => '31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '1.0.x-dev',
            'version' => '1.0.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'reference' => '9513098641797ce5f459dbc1de5a54c29b0ec1fb',
            'dev_requirement' => true,
        ),
        'phpunit/php-token-stream' => array(
            'pretty_version' => '1.4.12',
            'version' => '1.4.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-token-stream',
            'aliases' => array(),
            'reference' => '1ce90ba27c42e4e44e6d8458241466380b51fa16',
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '4.8.36',
            'version' => '4.8.36.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'reference' => '46023de9a91eec7dfb06cc56cb4e260017298517',
            'dev_requirement' => true,
        ),
        'phpunit/phpunit-mock-objects' => array(
            'pretty_version' => '2.3.x-dev',
            'version' => '2.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit-mock-objects',
            'aliases' => array(),
            'reference' => 'ac8e7a3db35738d56ee9a76e78a4e03d97628983',
            'dev_requirement' => true,
        ),
        'psr/cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'reference' => 'd11b50ad223250cf17b86e38383413f5a6764bf8',
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '1.x-dev',
            'version' => '1.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'reference' => '513e0666f7216c7459170d56df27dfcefe1689ea',
            'dev_requirement' => false,
        ),
        'psr/http-client' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'reference' => '22b2ef5687f43679481615605d7a15c557ce85b1',
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'reference' => '5a4f141ac2e5bc35e615134f127e1833158d2944',
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(
                0 => '1.0.x-dev',
            ),
            'reference' => 'efd67d1dc14a7ef4fc4e518e7dee91c271d524e4',
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => 'fe0936ee26643249e916849d48e3a51d5f5e278b',
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
            ),
        ),
        'psy/psysh' => array(
            'pretty_version' => 'v0.7.2',
            'version' => '0.7.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psy/psysh',
            'aliases' => array(),
            'reference' => 'e64e10b20f8d229cac76399e1f3edddb57a0f280',
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'dev_requirement' => false,
        ),
        'ramsey/uuid' => array(
            'pretty_version' => '3.x-dev',
            'version' => '3.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/uuid',
            'aliases' => array(),
            'reference' => 'dc75aa439eb4c1b77f5379fd958b3dc0e6014178',
            'dev_requirement' => false,
        ),
        'rhumsaa/uuid' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.x-dev',
            ),
        ),
        'rize/uri-template' => array(
            'pretty_version' => '0.3.5',
            'version' => '0.3.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../rize/uri-template',
            'aliases' => array(),
            'reference' => '5ed4ba8ea34af84485dea815d4b6b620794d1168',
            'dev_requirement' => false,
        ),
        'sabberworm/php-css-parser' => array(
            'pretty_version' => '8.4.0',
            'version' => '8.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabberworm/php-css-parser',
            'aliases' => array(),
            'reference' => 'e41d2140031d533348b2192a83f02d8dd8a71d30',
            'dev_requirement' => false,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '1.2.x-dev',
            'version' => '1.2.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'reference' => '18a5d97c25f408f48acaf6d1b9f4079314c5996a',
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '1.4.x-dev',
            'version' => '1.4.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'reference' => '7f066a26a962dbe58ddea9f72a4e82874a3975a4',
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '1.3.8',
            'version' => '1.3.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'reference' => 'be2c607e43ce4c89ecd60e75c6a85c126e754aea',
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'reference' => '42c4c2eec485ee3e159ec9884f95b431287edde4',
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '1.1.x-dev',
            'version' => '1.1.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'reference' => 'cea85a84b00f2795341ebbbca4fa396347f2494e',
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '1.0.x-dev',
            'version' => '1.0.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'reference' => 'b19cc3298482a335a95f3016d2f8a6950f0fbcd7',
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '1.0.6',
            'version' => '1.0.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'reference' => '58b3a85e7999757d6ad81c787a1fbf5ff6c628c6',
            'dev_requirement' => true,
        ),
        'sentry/sdk' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'type' => 'metapackage',
            'install_path' => NULL,
            'aliases' => array(),
            'reference' => '089858b1b27d3705a5fd1c32d8d10beb55980190',
            'dev_requirement' => false,
        ),
        'sentry/sentry' => array(
            'pretty_version' => '2.x-dev',
            'version' => '2.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sentry/sentry',
            'aliases' => array(),
            'reference' => 'ce63f13e2cf9f72ec169413545a3f7312b2e45e3',
            'dev_requirement' => false,
        ),
        'sentry/sentry-laravel' => array(
            'pretty_version' => '1.8.0',
            'version' => '1.8.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sentry/sentry-laravel',
            'aliases' => array(),
            'reference' => '912731d2b704fb6a97cef89c7a8b5c367cbf6088',
            'dev_requirement' => false,
        ),
        'stripe/stripe-php' => array(
            'pretty_version' => 'v6.43.1',
            'version' => '6.43.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stripe/stripe-php',
            'aliases' => array(),
            'reference' => '42fcdaf99c44bb26937223f8eae1f263491d5ab8',
            'dev_requirement' => false,
        ),
        'swiftmailer/swiftmailer' => array(
            'pretty_version' => '5.x-dev',
            'version' => '5.9999999.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../swiftmailer/swiftmailer',
            'aliases' => array(),
            'reference' => '181b89f18a90f8925ef805f950d47a7190e9b950',
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => '2.7.x-dev',
            'version' => '2.7.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'reference' => '574cb4cfaa01ba115fc2fc0c2355b2c5472a4804',
            'dev_requirement' => false,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => '2.8.x-dev',
            'version' => '2.8.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'reference' => '7b1692e418d7ccac24c373528453bc90e42797de',
            'dev_requirement' => false,
        ),
        'symfony/debug' => array(
            'pretty_version' => '2.7.x-dev',
            'version' => '2.7.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/debug',
            'aliases' => array(),
            'reference' => '4a7330f29b3d215f8bacf076689f9d1c3d568681',
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => '2.5.x-dev',
            'version' => '2.5.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'reference' => 'e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
            'dev_requirement' => false,
        ),
        'symfony/dom-crawler' => array(
            'pretty_version' => '2.7.x-dev',
            'version' => '2.7.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dom-crawler',
            'aliases' => array(),
            'reference' => 'd905e1c5885735ee66af60c205429b9941f24752',
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => '2.8.x-dev',
            'version' => '2.8.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'reference' => 'a77e974a5fecb4398833b0709210e3d5e334ffb0',
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => '2.7.x-dev',
            'version' => '2.7.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'reference' => '34226a3aa279f1e356ad56181b91acfdc9a2525c',
            'dev_requirement' => false,
        ),
        'symfony/http-client' => array(
            'pretty_version' => '5.4.x-dev',
            'version' => '5.4.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-client',
            'aliases' => array(),
            'reference' => '772129f800fc0bfaa6bd40c40934d544f0957d30',
            'dev_requirement' => false,
        ),
        'symfony/http-client-contracts' => array(
            'pretty_version' => '2.5.x-dev',
            'version' => '2.5.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-client-contracts',
            'aliases' => array(),
            'reference' => 'ba6a9f0e8f3edd190520ee3b9a958596b6ca2e70',
            'dev_requirement' => false,
        ),
        'symfony/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.4',
            ),
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => '2.7.x-dev',
            'version' => '2.7.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'reference' => 'b67e5cbd2bf837fb3681f2c4965826d6c6758532',
            'dev_requirement' => false,
        ),
        'symfony/http-kernel' => array(
            'pretty_version' => '2.7.x-dev',
            'version' => '2.7.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-kernel',
            'aliases' => array(),
            'reference' => '435064b3b143f79469206915137c21e88b56bfb9',
            'dev_requirement' => false,
        ),
        'symfony/options-resolver' => array(
            'pretty_version' => '5.4.x-dev',
            'version' => '5.4.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/options-resolver',
            'aliases' => array(),
            'reference' => '54f14e36aa73cb8f7261d7686691fd4d75ea2690',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(
                0 => '1.27.x-dev',
            ),
            'reference' => '5bbc823adecdae860bb64756d639ecfec17b050a',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(
                0 => '1.27.x-dev',
            ),
            'reference' => '639084e360537a19f9ee352433b84ce831f3d2da',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(
                0 => '1.27.x-dev',
            ),
            'reference' => '19bd1e4fcd5b91116f14d8533c57831ed00571b6',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(
                0 => '1.27.x-dev',
            ),
            'reference' => '8ad114f6b39e2c98a8b0e3bd907732c207c2b534',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php56' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'metapackage',
            'install_path' => NULL,
            'aliases' => array(
                0 => '1.20.x-dev',
            ),
            'reference' => '54b8cd7e6c1643d78d011f3be89f3ef1f9f4c675',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(
                0 => '1.27.x-dev',
            ),
            'reference' => '869329b1e9894268a8a61dabb69153029b7a8c97',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(
                0 => '1.27.x-dev',
            ),
            'reference' => '9e8ecb5f92152187c4799efd3c96b78ccab18ff9',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(
                0 => '1.27.x-dev',
            ),
            'reference' => '7a6ff3f1959bb01aefccb463a0f2cd3d3d2fd936',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-uuid' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-uuid',
            'aliases' => array(
                0 => '1.27.x-dev',
            ),
            'reference' => 'f3cf1a645c2734236ed1e2e671e273eeb3586166',
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => '2.7.x-dev',
            'version' => '2.7.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'reference' => 'eda637e05670e2afeec3842dcd646dce94262f6b',
            'dev_requirement' => false,
        ),
        'symfony/routing' => array(
            'pretty_version' => '2.7.x-dev',
            'version' => '2.7.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/routing',
            'aliases' => array(),
            'reference' => '33bd5882f201f9a3b7dd9640b95710b71304c4fb',
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => '2.5.x-dev',
            'version' => '2.5.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'reference' => '4b426aac47d6427cc1a1d0f7e2ac724627f5966c',
            'dev_requirement' => false,
        ),
        'symfony/translation' => array(
            'pretty_version' => '2.7.x-dev',
            'version' => '2.7.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation',
            'aliases' => array(),
            'reference' => '1959c78c5a32539ef221b3e18a961a96d949118f',
            'dev_requirement' => false,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => '2.7.x-dev',
            'version' => '2.7.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'reference' => '6f9271e94369db05807b261fcfefe4cd1aafd390',
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => '3.3.x-dev',
            'version' => '3.3.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'reference' => 'af615970e265543a26ee712c958404eb9b7ac93d',
            'dev_requirement' => true,
        ),
        'telnyx/telnyx-php' => array(
            'pretty_version' => 'v0.0.1',
            'version' => '0.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../telnyx/telnyx-php',
            'aliases' => array(),
            'reference' => 'deec64e7ccba5d299a660deb3f5c2687749839b6',
            'dev_requirement' => false,
        ),
        'twilio/sdk' => array(
            'pretty_version' => '5.42.2',
            'version' => '5.42.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twilio/sdk',
            'aliases' => array(),
            'reference' => '0cfcb871b18a9c427dd9e8f0ed7458d43009b48a',
            'dev_requirement' => false,
        ),
        'tymon/jwt-auth' => array(
            'pretty_version' => '0.5.12',
            'version' => '0.5.12.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tymon/jwt-auth',
            'aliases' => array(),
            'reference' => '614ee3410a1cc18ef13c8d5ffd491b5608afabd8',
            'dev_requirement' => false,
        ),
        'vlucas/phpdotenv' => array(
            'pretty_version' => '1.1.x-dev',
            'version' => '1.1.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../vlucas/phpdotenv',
            'aliases' => array(),
            'reference' => '0cac554ce06277e33ddf9f0b7ade4b8bbf2af3fa',
            'dev_requirement' => false,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'reference' => '11cb2199493b2f8a3b53e7f19068fc6aac760991',
            'dev_requirement' => false,
        ),
        'yajra/laravel-datatables-oracle' => array(
            'pretty_version' => 'v5.12.5',
            'version' => '5.12.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yajra/laravel-datatables-oracle',
            'aliases' => array(),
            'reference' => '4cc8d86de795af03c5f320711a9645b8a295b95f',
            'dev_requirement' => false,
        ),
    ),
);
